language: rust
os:
    - linux
    - osx
env:
    global:
        - LD_LIBRARY_PATH: /usr/local/lib
install:
    # Install PhysFS
    - curl -O http://icculus.org/physfs/downloads/physfs-2.0.3.tar.bz2
    - tar -jxf physfs-2.0.3.tar.bz2
    - cd physfs-2.0.3
    - cmake -G "Unix Makefiles"
    - make && sudo make install
before_script:
    - rustc -v
    - cargo -V
script:
    - cargo build -v
    - cargo test -v
