language: rust
os:
    - linux
    - osx
env:
    global:
        - LD_LIBRARY_PATH: /usr/local/lib
        - secure: gEfvLnzfT9U2IEqB6nL39wozQK5KFcJfOh+Pk06j4Ml4Arn7ZQAob/hI+QbPa9xspVl7xYJk+LU1jKzOlka5WiEnU39EwgVowhJxIbqmhvTCUhGv/YIpMCAdA8++FQJMXtC1YUcBjyj2IuZGQIZdu1bfmZCznodZpaE45OzMpqw=
install:
    # Install PhysFS
    - curl -O http://icculus.org/physfs/downloads/physfs-2.0.3.tar.bz2
    - tar -jxf physfs-2.0.3.tar.bz2
    - cd physfs-2.0.3
    - cmake -G "Unix Makefiles"
    - make && sudo make install
before_script:
    - rustc -v
    - cargo -V
script:
    - cargo build -v
    - cargo test -v
    - cargo doc -v
after_success:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
